# Generated by Django 4.2.3 on 2023-10-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0006_alter_promotion_type_prom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.CharField(choices=[('True', 'Verdadero'), ('False', 'Falso')], default=False, max_length=6, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
