# Generated by Django 4.2.3 on 2023-10-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0009_promotion_created_at_promotion_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
