# Generated by Django 4.2.3 on 2023-08-15 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('from_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='branches.branch')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
