# Generated by Django 4.2.3 on 2023-08-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employes", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="name",
            new_name="first_name",
        ),
    ]
