# Generated by Django 4.2.3 on 2023-09-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0003_alter_employee_options_remove_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_objetives',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_objetives', to='employes.employee', verbose_name='Empleado'),
        ),
    ]
