# Generated by Django 4.2.3 on 2023-08-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0004_alter_employee_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
