# Generated by Django 4.2.3 on 2023-08-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0007_rename_name_employee_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='from_branch',
        ),
    ]
