# Generated by Django 4.2.3 on 2023-11-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_objetives_branch'),
        ('employes', '0007_employee_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_objetives',
            name='objetive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_employees', to='core.objetives', verbose_name='Objetivo'),
        ),
    ]
