# Generated by Django 4.2.3 on 2023-10-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_delete_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telefono de contacto'),
        ),
    ]
