# Generated by Django 4.2.3 on 2023-11-11 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_rename_banks_supplier_bank_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier_bank',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='suppliers.cbu', verbose_name='Banco asociado'),
        ),
    ]
