# Generated by Django 4.2.3 on 2023-08-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoice_user_made_orderdetaill_user_made_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user_made',
        ),
        migrations.RemoveField(
            model_name='orderdetaill',
            name='user_made',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user_made',
        ),
        migrations.RemoveField(
            model_name='paymentmethod_sale',
            name='user_made',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='user_made',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='user_made',
        ),
    ]
