# Generated by Django 4.2.3 on 2023-10-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_orderdetail_discount_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='sell',
            new_name='sale',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='product',
        ),
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Descuento'),
        ),
    ]
