# Generated by Django 4.2.3 on 2023-10-16 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_product_has_eyeglass_frames'),
        ('sales', '0003_rename_sell_orderdetail_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='branch',
        ),
        migrations.AddField(
            model_name='promotion',
            name='productA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_product_A', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='productB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_product_B', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='type_discount',
            field=models.CharField(blank=True, choices=[('2X1', '2X1'), ('-50% 2da unidad', '-50% 2da unidad'), ('DESCUENTO %', 'DESCUENTO %')], default='2X1', max_length=15, null=True, verbose_name='Tipo de promocion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio'),
        ),
    ]
