# Generated by Django 4.2.3 on 2023-10-16 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_objetives_managers'),
        ('sales', '0005_remove_promotion_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='type_discount',
            field=models.CharField(blank=True, choices=[('2x1', '2x1'), ('-50% 2da unidad', '-50% 2da unidad'), ('DESCUENTO %', 'DESCUENTO %')], default='2X1', max_length=15, null=True, verbose_name='Tipo de promocion'),
        ),
    ]
