# Generated by Django 4.2.3 on 2023-10-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_invoicetype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetype',
            name='id',
            field=models.CharField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
