# Generated by Django 4.2.3 on 2023-10-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_invoicetype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetype',
            name='num_invoice',
            field=models.CharField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoicetype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
