# Generated by Django 4.2.3 on 2023-10-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_remove_sale_date_time_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount_extra',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Descuento'),
        ),
    ]
