# Generated by Django 4.2.3 on 2023-11-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afip', '0012_optionaltype_optional_alter_code_in_generics'),
        ('sales', '0023_alter_sale_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='client',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='user_made',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='invoice',
        ),
        migrations.AlterField(
            model_name='sale',
            name='receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='afip.receipt'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
