# Generated by Django 4.2.3 on 2023-08-22 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('white', models.BooleanField()),
                ('full_gray', models.BooleanField()),
                ('gray_gradient', models.BooleanField()),
                ('flat_sepia', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lej_od_esferico', models.CharField(blank=True, max_length=10, null=True)),
                ('lej_od_cilindrico', models.CharField(blank=True, max_length=10, null=True)),
                ('lej_od_eje', models.CharField(blank=True, max_length=10, null=True)),
                ('lej_oi_esferico', models.CharField(blank=True, max_length=10, null=True)),
                ('lej_oi_cilindrico', models.CharField(blank=True, max_length=10, null=True)),
                ('lej_oi_eje', models.CharField(blank=True, max_length=10, null=True)),
                ('cer_od_esferico', models.CharField(blank=True, max_length=10, null=True)),
                ('cer_od_cilindrico', models.CharField(blank=True, max_length=10, null=True)),
                ('cer_od_eje', models.CharField(blank=True, max_length=10, null=True)),
                ('cer_oi_esferico', models.CharField(blank=True, max_length=10, null=True)),
                ('cer_oi_cilindrico', models.CharField(blank=True, max_length=10, null=True)),
                ('cer_oi_eje', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cristal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('monofocal', models.BooleanField()),
                ('bifocal_fv', models.BooleanField()),
                ('bifocal_k', models.BooleanField()),
                ('bifocal_pi', models.BooleanField()),
                ('progressive', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interpupillary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lej_od_nanopupilar', models.CharField(blank=True, max_length=10, null=True)),
                ('lej_od_pelicula', models.CharField(blank=True, max_length=10, null=True)),
                ('lej_oi_nanopupilar', models.CharField(blank=True, max_length=10, null=True)),
                ('lej_oi_pelicula', models.CharField(blank=True, max_length=10, null=True)),
                ('lej_total', models.CharField(blank=True, max_length=10, null=True)),
                ('cer_od_nanopupilar', models.CharField(blank=True, max_length=10, null=True)),
                ('cer_od_pelicula', models.CharField(blank=True, max_length=10, null=True)),
                ('cer_oi_nanopupilar', models.CharField(blank=True, max_length=10, null=True)),
                ('cer_oi_pelicula', models.CharField(blank=True, max_length=10, null=True)),
                ('cer_total', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('policarbonato', models.BooleanField()),
                ('organic', models.BooleanField()),
                ('mineral', models.BooleanField()),
                ('m_r8', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tratamient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('antireflex', models.BooleanField()),
                ('filtro_azul', models.BooleanField()),
                ('fotocromatico', models.BooleanField()),
                ('ultravex', models.BooleanField()),
                ('polarizado', models.BooleanField()),
                ('neutrosolar', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Calibration_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('armazon', models.CharField(max_length=100)),
                ('observations', models.CharField(max_length=200)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.color')),
                ('correction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.correction')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='employes.employee')),
                ('interpupillary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.interpupillary')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.material')),
                ('medical_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.medicalhistory')),
                ('tratamient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.tratamient')),
                ('type_cristal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.cristal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
