# Generated by Django 4.2.5 on 2023-09-08 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_customer_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration_order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clients.customer', verbose_name='client'),
        ),
    ]
