# Generated by Django 4.2.3 on 2023-08-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_customer_options_remove_customer_person_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='healthinsurance',
            options={'verbose_name': 'Obra Socail', 'verbose_name_plural': 'Obras Socailes'},
        ),
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'verbose_name': 'Historia medico', 'verbose_name_plural': 'Historiales Medico'},
        ),
    ]
