# Generated by Django 4.2.3 on 2023-08-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_color_correction_cristal_interpupillary_material_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="name",
            new_name="first_name",
        ),
    ]
