# Generated by Django 4.2.3 on 2023-08-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_initial'),
        ('clients', '0002_color_correction_cristal_interpupillary_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibration_order',
            name='armazon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calibration_order',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.color'),
        ),
        migrations.AlterField(
            model_name='calibration_order',
            name='correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.correction'),
        ),
        migrations.AlterField(
            model_name='calibration_order',
            name='employees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='employes.employee'),
        ),
        migrations.AlterField(
            model_name='calibration_order',
            name='interpupillary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.interpupillary'),
        ),
        migrations.AlterField(
            model_name='calibration_order',
            name='is_done',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='calibration_order',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.material'),
        ),
        migrations.AlterField(
            model_name='calibration_order',
            name='medical_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.medicalhistory'),
        ),
        migrations.AlterField(
            model_name='calibration_order',
            name='observations',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='calibration_order',
            name='tratamient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.tratamient'),
        ),
        migrations.AlterField(
            model_name='calibration_order',
            name='type_cristal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.cristal'),
        ),
        migrations.AlterField(
            model_name='color',
            name='flat_sepia',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='full_gray',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='gray_gradient',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='white',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cristal',
            name='bifocal_fv',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cristal',
            name='bifocal_k',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cristal',
            name='bifocal_pi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cristal',
            name='monofocal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cristal',
            name='progressive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='m_r8',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='mineral',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='organic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='policarbonato',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamient',
            name='antireflex',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamient',
            name='filtro_azul',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamient',
            name='fotocromatico',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamient',
            name='neutrosolar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamient',
            name='polarizado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tratamient',
            name='ultravex',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
