# Generated by Django 4.2.3 on 2023-08-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_calibration_order_armazon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibration_order',
            name='medical_details',
        ),
        migrations.AddField(
            model_name='calibration_order',
            name='diagnostic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='MedicalHistory',
        ),
    ]
