# Generated by Django 4.2.3 on 2023-08-29 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employes", "0004_employee_user_made_alter_employee_from_branch_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0003_rename_name_customer_first_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calibration_order",
            name="medical_details",
        ),
        migrations.AddField(
            model_name="calibration_order",
            name="diagnostic",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="calibration_order",
            name="user_made",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="color",
            name="user_made",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="correction",
            name="user_made",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cristal",
            name="user_made",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="user_made",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer_healthinsurance",
            name="user_made",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="healthinsurance",
            name="phone_number",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthinsurance",
            name="user_made",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interpupillary",
            name="user_made",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="user_made",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tratamient",
            name="user_made",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="calibration_order",
            name="armazon",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="calibration_order",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="laboratory",
                to="clients.color",
            ),
        ),
        migrations.AlterField(
            model_name="calibration_order",
            name="correction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="laboratory",
                to="clients.correction",
            ),
        ),
        migrations.AlterField(
            model_name="calibration_order",
            name="employees",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="laboratory",
                to="employes.employee",
            ),
        ),
        migrations.AlterField(
            model_name="calibration_order",
            name="interpupillary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="laboratory",
                to="clients.interpupillary",
            ),
        ),
        migrations.AlterField(
            model_name="calibration_order",
            name="is_done",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="calibration_order",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="laboratory",
                to="clients.material",
            ),
        ),
        migrations.AlterField(
            model_name="calibration_order",
            name="observations",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="calibration_order",
            name="tratamient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="laboratory",
                to="clients.tratamient",
            ),
        ),
        migrations.AlterField(
            model_name="calibration_order",
            name="type_cristal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="laboratory",
                to="clients.cristal",
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="flat_sepia",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="color",
            name="full_gray",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="color",
            name="gray_gradient",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="color",
            name="white",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cristal",
            name="bifocal_fv",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cristal",
            name="bifocal_k",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cristal",
            name="bifocal_pi",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cristal",
            name="monofocal",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cristal",
            name="progressive",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="m_r8",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="mineral",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="organic",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="material",
            name="policarbonato",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tratamient",
            name="antireflex",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tratamient",
            name="filtro_azul",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tratamient",
            name="fotocromatico",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tratamient",
            name="neutrosolar",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tratamient",
            name="polarizado",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tratamient",
            name="ultravex",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="MedicalHistory",
        ),
    ]
