# Generated by Django 4.2.3 on 2023-08-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_calibration_order_user_made_color_user_made_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthinsurance',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
