# Generated by Django 4.2.3 on 2023-08-25 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_healthinsurance_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
    ]
