# Generated by Django 4.2.3 on 2023-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_customer_phone_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurance',
            name='cuit',
            field=models.CharField(max_length=20, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='healthinsurance',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Obra Social'),
        ),
        migrations.AlterField(
            model_name='healthinsurance',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
