# Generated by Django 4.2.3 on 2023-08-26 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_material_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={},
        ),
    ]
