# Generated by Django 4.2.3 on 2023-10-05 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0010_customer_credit_balance_customer_has_credit_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('diagnostic', models.CharField(blank=True, max_length=200, null=True, verbose_name='Diagnostico')),
                ('armazon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Armazon')),
                ('observations', models.CharField(blank=True, max_length=200, null=True, verbose_name='Observacion')),
                ('is_done', models.BooleanField(blank=True, default=False, null=True, verbose_name='Estado')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.color')),
                ('correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.correction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='credit_balance',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='has_credit_account',
        ),
        migrations.DeleteModel(
            name='Calibration_Order',
        ),
        migrations.DeleteModel(
            name='CreditTransaction',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='serviceorders', to='clients.customer', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='interpupillary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.interpupillary'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.material'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='tratamient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.tratamient'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='type_cristal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory', to='clients.cristal'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por'),
        ),
    ]
