# Generated by Django 4.2.3 on 2023-10-05 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_serviceorder_remove_credittransaction_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceorders', to='clients.customer', verbose_name='Cliente'),
        ),
    ]
