# Generated by Django 4.2.3 on 2023-10-23 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_sale_missing_balance'),
        ('clients', '0011_serviceorder_delete_calibration_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.sale'),
        ),
    ]
