# Generated by Django 4.2.3 on 2023-11-03 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_cost_price_alter_product_sale_price'),
        ('clients', '0014_serviceorder_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='armazon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_order', to='products.product'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_order', to='clients.color'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_order', to='clients.correction'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='interpupillary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_order', to='clients.interpupillary'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_order', to='clients.material'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='tratamient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_order', to='clients.tratamient'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='type_cristal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_order', to='clients.cristal'),
        ),
    ]
