# Generated by Django 4.2.3 on 2023-09-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objetives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('to', models.CharField(blank=True, choices=[('EMPLEADOS', 'EMPLEADOS'), ('SUCURSAL', 'SUCURSAL')], default='EMPLEADOS', max_length=9, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Detalle de Objetivo')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Validez Inicio')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='Validez Finalizacion')),
                ('quantity', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Objetivo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
