# Generated by Django 4.2.3 on 2023-09-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetives',
            old_name='type',
            new_name='title',
        ),
    ]
