# Generated by Django 4.2.3 on 2023-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_type_objetives_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetives',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Objetivo'),
        ),
    ]
