# Generated by Django 4.2.3 on 2023-08-28 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_remove_branch_created_at_remove_branch_deleted_at_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='from_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('EMPLEADOR', 'EM'), ('ADMINISTRADOR', 'AD')], default='EM', max_length=15, null=True),
        ),
    ]
