# Generated by Django 4.2.3 on 2023-08-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_from_branch_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='from_branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
