# Generated by Django 4.2.3 on 2023-08-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_remove_branch_created_at_remove_branch_deleted_at_and_more'),
        ('users', '0003_remove_user_from_branch_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'AD'), ('EMPLEADO', 'EM')], default='EM', max_length=15, null=True),
        ),
    ]
