# Generated by Django 4.2.3 on 2023-08-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_branch_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('EMPLEADO', 'EMPLEADO')], default='EMPLEADO', max_length=15, null=True),
        ),
    ]
