# Generated by Django 4.2.3 on 2023-09-18 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_phone_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
