# Generated by Django 4.2.3 on 2023-09-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_supplier',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_suppliers', to='products.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='product_supplier',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_suppliers', to='suppliers.supplier', verbose_name='Proveedor'),
        ),
    ]
