# Generated by Django 4.2.3 on 2023-08-30 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_brand_user_made_category_user_made_feature_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_supplier",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_suppliers",
                to="products.product",
                verbose_name="Producto",
            ),
        ),
        migrations.AddField(
            model_name="product_supplier",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_suppliers",
                to="suppliers.supplier",
                verbose_name="Proveedor",
            ),
        ),
        migrations.AddField(
            model_name="product_supplier",
            name="user_made",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="user_made",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
