# Generated by Django 4.2.3 on 2023-09-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_product_supplier_user_made_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='COD.Pais'),
        ),
    ]
