# Generated by Django 4.2.3 on 2023-10-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_promotion'),
        ('suppliers', '0005_brand_supplier_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_supplier',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_suppliers', to='products.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='brand_supplier',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_suppliers', to='suppliers.supplier', verbose_name='Proveedor'),
        ),
    ]
