# Generated by Django 4.2.3 on 2023-10-26 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_bank_created_at_bank_deleted_at_bank_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Supplier',
        ),
    ]
