# Generated by Django 4.2.3 on 2023-11-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0010_remove_bank_supplier_brand_supplier_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telefono de contacto'),
        ),
    ]
