# Generated by Django 4.2.3 on 2023-11-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0012_remove_bank_cbu_remove_bank_cuit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del Banco'),
        ),
        migrations.AlterField(
            model_name='cbu',
            name='cbu',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ALIAS/CBU/CVU'),
        ),
    ]
