# Generated by Django 4.2.3 on 2023-11-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0013_alter_bank_bank_name_alter_cbu_cbu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbu',
            name='cbu',
            field=models.CharField(max_length=20, unique=True, verbose_name='ALIAS/CBU/CVU'),
        ),
    ]
