# Generated by Django 4.2.3 on 2023-11-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0017_alter_supplier_bank_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbu',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cbu',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='cbu',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cbu',
            name='user_made',
        ),
    ]
