# Generated by Django 4.2.3 on 2023-11-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0018_remove_cbu_created_at_remove_cbu_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier_bank',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplier_bank',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='supplier_bank',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='supplier_bank',
            name='user_made',
        ),
    ]
