# Generated by Django 4.2.3 on 2023-09-13 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Branch_Objetives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_completed', models.BooleanField(blank=True, default=False, verbose_name='Completado')),
                ('accumulated', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Acumulado')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Sucursal')),
                ('objetive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.objetives', verbose_name='Objetivo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
