# Generated by Django 4.2.3 on 2023-08-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="branch",
            name="updated_at",
        ),
    ]
