# Generated by Django 4.2.3 on 2023-09-28 16:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_created_at_branch_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='branch_objetives',
            managers=[
                ('active_objectives', django.db.models.manager.Manager()),
            ],
        ),
    ]
