# Generated by Django 4.2.3 on 2023-08-24 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0002_branch_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='user',
        ),
        migrations.AddField(
            model_name='branch',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
