# Generated by Django 4.2.3 on 2023-08-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_remove_branch_user_branch_user_made'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='user_made',
        ),
    ]
