# Generated by Django 4.2.3 on 2023-10-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre de Sucursal'),
        ),
    ]
