# Generated by Django 4.2.3 on 2023-11-07 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0005_alter_branch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch_objetives',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por'),
        ),
    ]
