# Generated by Django 4.2.3 on 2023-11-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_branch_pos_afip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch_objetives',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_objetives', to='branches.branch', verbose_name='Sucursal'),
        ),
    ]
