# Generated by Django 4.2.3 on 2023-10-16 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0015_alter_product_has_eyeglass_frames'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branches', '0003_alter_branch_objetives_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('type_discount', models.CharField(blank=True, choices=[('A', '2x1'), ('B', '-50% 2da unidad'), ('C', 'DESCUENTO %')], default=('C', 'DESCUENTO %'), max_length=15, null=True, verbose_name='Tipo de promocion')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fin')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Sucursal')),
                ('productA', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_product_A', to='products.product', verbose_name='Producto')),
                ('productB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_product_B', to='products.product', verbose_name='Producto')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
