# Generated by Django 4.2.3 on 2023-10-20 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0016_alter_product_promotion'),
        ('promotions', '0003_alter_promotion_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='productA',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='productB',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='type_discount',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='user_made',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la Promoción'),
        ),
        migrations.CreateModel(
            name='TypePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de Promoción')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='products.product')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_products', to='promotions.promotion')),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='type_prom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.typepromotion', verbose_name='Tipo de promoción'),
        ),
    ]
