# Generated by Django 4.2.3 on 2023-10-20 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0005_promotion_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='type_prom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promotions.typepromotion', verbose_name='Tipo de promoción'),
        ),
    ]
