# Generated by Django 4.2.3 on 2023-10-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_alter_promotion_is_active_alter_promotion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Activo'),
        ),
    ]
