# Generated by Django 4.2.3 on 2023-09-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_customer_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
