# Generated by Django 4.2.3 on 2023-09-22 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_created_at_branch_deleted_at_and_more'),
        ('clients', '0008_alter_healthinsurance_cuit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='branches.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.CharField(db_index=True, max_length=20, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='COD.Pais'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
