# Generated by Django 4.2.3 on 2023-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_alter_serviceorder_armazon_alter_serviceorder_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthinsurance',
            options={'verbose_name': 'Obra Social', 'verbose_name_plural': 'Obras Sociales'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
    ]
