# Generated by Django 4.2.3 on 2023-08-22 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Supplier',
        ),
    ]
