# Generated by Django 4.2.3 on 2023-08-21 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_feature_type_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature_type',
            old_name='characteristic',
            new_name='category',
        ),
    ]
