# Generated by Django 4.2.3 on 2023-08-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('products', '0003_rename_characteristic_feature_type_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Caracteristica', 'verbose_name_plural': 'Caracteristicas'},
        ),
        migrations.AlterModelOptions(
            name='feature_type',
            options={'verbose_name': 'Tipo Caracteristica', 'verbose_name_plural': 'Tipos Caracteristicas'},
        ),
        migrations.RemoveField(
            model_name='feature_type',
            name='category',
        ),
        migrations.AlterField(
            model_name='feature',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature', to='products.feature_type', verbose_name='Tipo de caracteristica'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='feature_type',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product_supplier',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_suppliers', to='products.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='product_supplier',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_suppliers', to='suppliers.supplier', verbose_name='Proveedor'),
        ),
    ]
