# Generated by Django 4.2.3 on 2023-08-25 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_feature_product_product_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_feature',
        ),
    ]
