# Generated by Django 4.2.3 on 2023-08-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_feature_options_alter_feature_type_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.product', verbose_name='Producto'),
            preserve_default=False,
        ),
    ]
