# Generated by Django 4.2.3 on 2023-08-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_feature_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='product',
        ),
    ]
