# Generated by Django 4.2.3 on 2023-08-22 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_feature_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='products.product', verbose_name='Producto'),
        ),
    ]
