# Generated by Django 4.2.3 on 2023-08-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_feature_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
    ]
