# Generated by Django 4.2.3 on 2023-10-13 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_rename_sell_orderdetail_sale_and_more'),
        ('products', '0012_alter_product_feature_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_promotion', to='sales.promotion', verbose_name='Promoción'),
        ),
    ]
