# Generated by Django 4.2.3 on 2023-08-19 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employes', '0005_remove_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esferic', models.CharField(blank=True, max_length=20, null=True)),
                ('cilindric', models.CharField(blank=True, max_length=20, null=True)),
                ('eje', models.CharField(blank=True, max_length=10, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employes.employee')),
            ],
            options={
                'verbose_name': 'Lejos',
                'abstract': False,
            },
        ),
    ]
