# Generated by Django 4.2.3 on 2023-08-19 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboratory',
            old_name='eje',
            new_name='other',
        ),
    ]
