# Generated by Django 4.2.3 on 2023-08-19 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_rename_eje_laboratory_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esferic', models.CharField(blank=True, max_length=20, null=True)),
                ('cilindric', models.CharField(blank=True, max_length=20, null=True)),
                ('other', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='laboratory',
            options={},
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='cilindric',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='esferic',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='other',
        ),
        migrations.CreateModel(
            name='Eye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='laboratory.correction')),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_left', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distance_left', to='laboratory.eye')),
                ('eye_right', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distance_right', to='laboratory.eye')),
            ],
        ),
        migrations.AddField(
            model_name='laboratory',
            name='distance_close',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_close', to='laboratory.distance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='distance_far',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_far', to='laboratory.distance'),
            preserve_default=False,
        ),
    ]
