# Generated by Django 4.2.3 on 2023-08-19 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_correction_alter_laboratory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='distance_close',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='distance_far',
        ),
        migrations.AddField(
            model_name='eye',
            name='distance_type',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eye',
            name='laboratory',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='laboratory.laboratory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eye',
            name='side',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Distance',
        ),
    ]
