# Generated by Django 4.2.3 on 2023-08-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_remove_laboratory_distance_close_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eye',
            name='correction',
        ),
        migrations.RemoveField(
            model_name='eye',
            name='laboratory',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Correction',
        ),
        migrations.DeleteModel(
            name='Eye',
        ),
        migrations.DeleteModel(
            name='Laboratory',
        ),
    ]
