# Generated by Django 4.2.3 on 2023-08-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0005_remove_eye_correction_remove_eye_laboratory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EyeCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('esferic', models.CharField(blank=True, max_length=20, null=True)),
                ('cilindric', models.CharField(blank=True, max_length=20, null=True)),
                ('eje', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Far',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('left_eye', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='far_left_eye', to='laboratory.eyecorrection')),
                ('right_eye', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='far_right_eye', to='laboratory.eyecorrection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Close',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('left_eye', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='close_left_eye', to='laboratory.eyecorrection')),
                ('right_eye', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='close_right_eye', to='laboratory.eyecorrection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
