# Generated by Django 4.2.3 on 2023-08-21 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Left_eye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('esferic', models.CharField(blank=True, max_length=20, null=True)),
                ('cilindric', models.CharField(blank=True, max_length=20, null=True)),
                ('eje', models.CharField(blank=True, max_length=10, null=True)),
                ('distance', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Right_eye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('esferic', models.CharField(blank=True, max_length=20, null=True)),
                ('cilindric', models.CharField(blank=True, max_length=20, null=True)),
                ('eje', models.CharField(blank=True, max_length=10, null=True)),
                ('distance', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='far',
            name='left_eye',
        ),
        migrations.RemoveField(
            model_name='far',
            name='right_eye',
        ),
        migrations.DeleteModel(
            name='Close',
        ),
        migrations.DeleteModel(
            name='EyeCorrection',
        ),
        migrations.DeleteModel(
            name='Far',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='left_eye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.left_eye'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='right_eye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratory.right_eye'),
        ),
    ]
