# Generated by Django 4.2.3 on 2023-09-11 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashregister', '0003_rename_transaction_id_movement_transaction_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeMethodePayment',
            new_name='PaymentType',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_refund',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='original_transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='refund_reason',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_number',
        ),
        migrations.AddField(
            model_name='transaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
