# Generated by Django 4.2.3 on 2023-10-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0006_alter_movement_type_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregisterdetail',
            name='counted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
