<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-09-07 13:57
=======
# Generated by Django 4.2.3 on 2023-09-07 06:06
>>>>>>> 8057cdb8de2af27191a3b8ab54121bd2551f8411

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('branches', '0001_initial'),
        ('cashregister', '0001_initial'),
=======
        ('cashregister', '0001_initial'),
        ('branches', '0001_initial'),
>>>>>>> 8057cdb8de2af27191a3b8ab54121bd2551f8411
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='typemethodepayment',
            name='user_made',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Hecho por'),
=======
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
>>>>>>> 8057cdb8de2af27191a3b8ab54121bd2551f8411
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='user_made',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Hecho por'),
=======
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
>>>>>>> 8057cdb8de2af27191a3b8ab54121bd2551f8411
        ),
        migrations.AddField(
            model_name='transaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashregister.transaction'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashregister.transactiontype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_made',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Hecho por'),
=======
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
>>>>>>> 8057cdb8de2af27191a3b8ab54121bd2551f8411
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='type_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashregister.typemethodepayment'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user_made',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Hecho por'),
=======
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
>>>>>>> 8057cdb8de2af27191a3b8ab54121bd2551f8411
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashregister.currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashregister.paymentmethod'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user_made',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Hecho por'),
=======
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
>>>>>>> 8057cdb8de2af27191a3b8ab54121bd2551f8411
        ),
        migrations.AddField(
            model_name='movement',
            name='cash_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashregister.cashregister', verbose_name='Caja'),
        ),
        migrations.AddField(
            model_name='movement',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashregister.currency', verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='movement',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashregister.paymentmethod', verbose_name='Metodo de pago'),
        ),
        migrations.AddField(
            model_name='movement',
            name='transaction_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashregister.transaction', verbose_name='Transacción'),
        ),
        migrations.AddField(
            model_name='movement',
            name='user_made',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Hecho por'),
=======
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
>>>>>>> 8057cdb8de2af27191a3b8ab54121bd2551f8411
        ),
        migrations.AddField(
            model_name='currency',
            name='user_made',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Hecho por'),
=======
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
>>>>>>> 8057cdb8de2af27191a3b8ab54121bd2551f8411
        ),
        migrations.AddField(
            model_name='cashregisterdetail',
            name='cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashregister.cashregister'),
        ),
        migrations.AddField(
            model_name='cashregisterdetail',
            name='type_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashregister.typemethodepayment'),
        ),
        migrations.AddField(
            model_name='cashregisterdetail',
            name='user_made',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Hecho por'),
=======
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
>>>>>>> 8057cdb8de2af27191a3b8ab54121bd2551f8411
        ),
        migrations.AddField(
            model_name='cashregister',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashregister.currency'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='user_made',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Hecho por'),
=======
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
>>>>>>> 8057cdb8de2af27191a3b8ab54121bd2551f8411
        ),
    ]
