# Generated by Django 4.2.3 on 2023-09-11 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashregister', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='transaction_id',
            new_name='transaction',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='counted_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de la caja fisica'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashregister.currency', verbose_name='Divisa'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='date_close',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha cierre'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='date_open',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha apertura'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferencia'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='final_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto final'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto inicial'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='is_close',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por'),
        ),
        migrations.AlterField(
            model_name='cashregisterdetail',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por'),
        ),
        migrations.AlterField(
            model_name='typemethodepayment',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por'),
        ),
    ]
