# Generated by Django 4.2.3 on 2023-08-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cashregister", "0002_cashregister_branch_cashregister_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashregister",
            name="is_active",
        ),
        migrations.AddField(
            model_name="cashregister",
            name="counted_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cashregister",
            name="difference",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
