# Generated by Django 4.2.3 on 2023-08-27 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "cashregister",
            "0003_transactiontype_remove_transaction_type_transaction_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="movement",
            name="withdrawal_reason",
            field=models.CharField(
                blank=True,
                help_text="Campo para ingresar el motivo de devolucion",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_refund",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="transaction",
            name="original_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cashregister.transaction",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="refund_reason",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
