# Generated by Django 4.2.3 on 2023-08-30 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cashregister", "0004_cashregisterdetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cashregisterdetail",
            name="payment_method",
        ),
        migrations.AddField(
            model_name="cashregisterdetail",
            name="type_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cashregister.typemethodepayment",
            ),
        ),
        migrations.AlterField(
            model_name="cashregisterdetail",
            name="cash_register",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cashregister.cashregister",
            ),
        ),
    ]
