# Generated by Django 4.2.3 on 2023-08-27 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "cashregister",
            "0004_movement_withdrawal_reason_transaction_is_refund_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="movement",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cashregister.paymentmethod",
            ),
        ),
    ]
