# Generated by Django 4.2.3 on 2023-08-27 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branches", "0001_initial"),
        ("cashregister", "0005_alter_movement_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashregister",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="branches.branch",
            ),
        ),
    ]
