# Generated by Django 4.2.3 on 2023-10-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0005_movement_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='type_operation',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=50, verbose_name='Operacion'),
        ),
    ]
