# Generated by Django 4.2.3 on 2023-08-27 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cashregister", "0006_alter_cashregister_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashregister",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cashregister.currency",
            ),
        ),
    ]
