# Generated by Django 4.2.3 on 2023-10-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0007_alter_cashregisterdetail_counted_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
