<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-09-07 13:57
=======
<<<<<<<< HEAD:project/applications/employes/migrations/0002_initial.py
# Generated by Django 4.2.3 on 2023-09-07 13:57
========
# Generated by Django 4.2.3 on 2023-09-07 06:06
>>>>>>>> 8057cdb8de2af27191a3b8ab54121bd2551f8411:project/applications/notes/migrations/0002_initial.py
>>>>>>> 8057cdb8de2af27191a3b8ab54121bd2551f8411

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user_made',
<<<<<<< HEAD
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Hecho por'),
=======
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='label',
            name='user_made',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
>>>>>>> 8057cdb8de2af27191a3b8ab54121bd2551f8411
        ),
    ]
