# Generated by Django 4.2.3 on 2023-08-21 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_address_alter_branch_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='branches.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(max_length=20, null=True, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
