# Generated by Django 4.2.3 on 2023-08-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(db_index=True, max_length=50)),
                ('phone_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('dni', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=55, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
