# Generated by Django 4.2.3 on 2023-08-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0003_alter_employee_options_remove_employee_person_and_more'),
        ('clients', '0002_alter_customer_options_remove_customer_person_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
