# Generated by Django 4.2.3 on 2023-11-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_branch_objetives_user_made'),
        ('core', '0004_objetives_user_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetives',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='branches.branch', verbose_name='Sucursal'),
        ),
    ]
