# Generated by Django 4.2.3 on 2023-10-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_promotion_branch_alter_promotion_type_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='type_discount',
            field=models.CharField(blank=True, choices=[('A', '2x1'), ('B', '-50% 2da unidad'), ('C', 'DESCUENTO %')], default='A', max_length=15, null=True, verbose_name='Tipo de promocion'),
        ),
    ]
