# Generated by Django 4.2.3 on 2023-10-16 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_promotion'),
        ('sales', '0007_alter_promotion_type_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
