# Generated by Django 4.2.3 on 2023-10-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_delete_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='missing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
