# Generated by Django 4.2.3 on 2023-10-24 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0011_payment_sale_payment_paymenttype_paymentmethod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceType',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, choices=[('A', 'Factura A'), ('B', 'Factura B'), ('X', 'Comprobante de pago')], default=('A', 'Factura A'), max_length=10, null=True)),
                ('user_made', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_payment', to='sales.sale'),
        ),
        migrations.DeleteModel(
            name='Sale_Payment',
        ),
    ]
