# Generated by Django 4.2.3 on 2023-10-24 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_delete_credittransaction'),
        ('sales', '0015_invoicetype_num_invoice_alter_invoicetype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='clients.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.invoicetype', verbose_name='Tipo de factura'),
        ),
    ]
