# Generated by Django 4.2.3 on 2023-10-26 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_phone'),
        ('sales', '0017_sale_date_time_sale_alter_sale_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='branches.branch'),
        ),
    ]
