# Generated by Django 4.2.3 on 2023-11-09 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_sale_discount_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
