# Generated by Django 4.2.3 on 2023-12-04 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0010_alter_movement_description'),
        ('sales', '0025_alter_sale_receipt_delete_invoicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='movement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mov_payment', to='cashregister.movement'),
        ),
    ]
