# Generated by Django 4.2.3 on 2023-12-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_alter_sale_commision_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_extra',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Descuento'),
        ),
    ]
