# Generated by Django 4.2.3 on 2023-12-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_alter_sale_discount_alter_sale_discount_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount_extra',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Descuento'),
        ),
    ]
