# Generated by Django 4.2.3 on 2023-12-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_alter_sale_discount_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='surcharge',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Recargo'),
        ),
    ]
