# Generated by Django 4.2.3 on 2023-10-13 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_product_suggested_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_feature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='features_of_product', to='products.feature', verbose_name='Caracteristica'),
        ),
    ]
