# Generated by Django 4.2.3 on 2023-10-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_eyeglass_frames',
            field=models.BooleanField(default=False),
        ),
    ]
