# Generated by Django 4.2.3 on 2023-10-16 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('products', '0015_alter_product_has_eyeglass_frames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_promotion', to='promotions.promotion', verbose_name='Promoción'),
        ),
    ]
